Fix compile when `PROGRESSUPDATE` is defined
  src/ai.cpp:196:12: error: use of undeclared identifier 'statGroup'
    196 |                                 if ((statGroup % PROGRESSUPDATE) == 0) {
        |                                      ^
  src/ai.cpp:197:21: error: use of undeclared identifier 'statGroup'
    197 |                 if (statGroup == 0 ) std::cerr << endl << endl;
        |                     ^
  src/ai.cpp:198:41: error: use of undeclared identifier 'statGroup'
    198 |                 std::cerr << "\rW: " << statGroup << "/" << statCount << "  \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\r" << flush;
        |                                         ^
  src/ai.cpp:198:61: error: use of undeclared identifier 'statCount'
    198 |                 std::cerr << "\rW: " << statGroup << "/" << statCount << "  \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\r" << flush;
        |                                                             ^
  src/ai.cpp:629:10: error: use of undeclared identifier 'statGroup'
    629 |     if ((statGroup % PROGRESSUPDATE) == 0) { showProgressUpdate(); }
        |          ^