Remove unused code
src/engine.cpp: In member function ‘float64 DealRemainder::AnalyzeComplete(PlayStats*)’:
src/engine.cpp:203:22: error: variable ‘pos’ set but not used [-Werror=unused-but-set-variable]
  203 |         DeckLocation pos;
      |                      ^~~